kind: BuildConfig
apiVersion: v1
metadata:
  name: starter-dev
  labels:
    name: starter-dev
spec:
  triggers:
  - type: GitHub
    github:
      secret: CHANGEME
  - type: Generic
    generic:
      secret: CHANGEME
  - type: ConfigChange
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          stage ('build') {
            openshiftBuild(buildConfig: 'starter-dev', showBuildLogs: 'true', namespace: 'starter-dev')
          }
          stage ('deploy') {
            openshiftDeloy(deployConfig: 'starter-dev', showBuildLogs: 'true', namespace: 'starter-dev')
          }
          stage ('test') {
            //openshiftBuild(buildConfig: 'edge-anki-twin-deploy', showBuildLogs: 'true', namespace: 'starter-dev')
          }
        }

