kind: BuildConfig
apiVersion: v1
metadata:
  name: starter-dev
  labels:
    name: starter-dev
spec:
  triggers:
  - type: GitHub
    github:
      secret: CHANGEME
  - type: Generic
    generic:
      secret: CHANGEME
  - type: ConfigChange
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
          echo 'Hello branch'
          //stage 'build'
          //openshiftBuild(buildConfig: 'edge-anki-twin-build', showBuildLogs: 'true', namespace: 'starter-dev')
          //stage 'push'
          //openshiftBuild(buildConfig: 'edge-anki-twin-push', showBuildLogs: 'true', namespace: 'edge-dev')
          //stage 'deploy'
          //openshiftBuild(buildConfig: 'edge-anki-twin-deploy', showBuildLogs: 'true', namespace: 'edge-dev')
        }

